version: '3'

services:
    reverse-proxy:
        image: traefik:latest
        container_name: traefik-reverse-proxy
        command:
            - --providers.file.filename=traefik-dynamic.toml
            - --providers.file.watch=true
            - --providers.docker=true
            - --entryPoints.web.address=:80
            - --entryPoints.websecure.address=:443
           #- --api.insecure=true
        ports:
            - 80:80
            - 443:443
           #- 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik-dynamic.toml:/traefik-dynamic.toml
            - ${CERTIFICATES_FOLDER}:/certificates:ro
        networks:
            - frontend
        restart: unless-stopped

    nextcloud-db:
        image: postgres:9-alpine
        container_name: nextcloud-db
        env_file: ./.servenv/nc-db-env
        volumes:
            - ${NEXTCLOUD_DB_FOLDER}:/var/lib/postgresql/data
        networks:
            - nextcloud
        restart: unless-stopped

    nextcloud:
        image: wonderfall/nextcloud:latest
        container_name: nextcloud
        env_file: ./.servenv/nc-env
        environment:
            - UID=${NEXTCLOUD_UID}
            - GID=${NEXTCLOUD_GID}
        ports:
            - 8888:8888
        labels:
            - "traefik.http.services.nextcloud.loadbalancer.server.port=8888"

            - "traefik.http.middlewares.ncstrip.stripprefix.prefixes=/nextcloud"

            - "traefik.http.routers.ncweb.entrypoints=web"
            - "traefik.http.routers.ncweb.service=nextcloud"
            - "traefik.http.routers.ncweb.rule=Host(`${NEXTCLOUD_DOMAIN}`) && PathPrefix(`/nextcloud`)"
            - "traefik.http.routers.ncweb.middlewares=redirectsecure@file"

            - "traefik.http.routers.ncwebsecure.entrypoints=websecure"
            - "traefik.http.routers.ncwebsecure.service=nextcloud"
            - "traefik.http.routers.ncwebsecure.rule=Host(`${NEXTCLOUD_DOMAIN}`) && PathPrefix(`/nextcloud`)"
            - "traefik.http.routers.ncwebsecure.tls=true"
            - "traefik.http.routers.ncwebsecure.tls.domains.main=default"
            - "traefik.http.routers.ncwebsecure.middlewares=ncstrip"
        volumes:
            - ${NEXTCLOUD_DATA_FOLDER}:/data
            - ${NEXTCLOUD_CONFIG_FOLDER}:/config
            - ${NEXTCLOUD_APP_FOLDER}:/apps2
        networks:
            - nextcloud
            - frontend
        depends_on:
            - nextcloud-db
        restart: unless-stopped

    samba:
        image: dperson/samba:latest
        container_name: samba
        environment:
            - USERID=${SAMBA_UID}
            - GROUPID=${SAMBA_GID}
            - WORKGROUP=WORKGROUP
        ports:
            - 139:139
            - 445:445
        volumes:
            - ${SAMBA_SHARES_FOLDER}:/shares
        command: ${SAMBA_COMMAND}
        restart: unless-stopped

    transmission:
        image: dperson/transmission:latest
        container_name: transmission
        environment:
            - TRUSER=${TRANSMISSION_USERNAME}
            - TRPASSWD=${TRANSMISSION_PASSWORD}
            - USERID=${TRANSMISSION_UID}
            - GROUPID=${TRANSMISSION_GID}
        ports:
            - 9091:9091
        volumes:
            - ${TRANSMISSION_INCOMPLETE_FOLDER}:/var/lib/transmission-daemon/incomplete
            - ${TRANSMISSION_DOWNLOADED_FOLDER}:/var/lib/transmission-daemon/downloads
        restart: unless-stopped

networks:
    frontend:
        driver: bridge
    nextcloud:
        driver: bridge
