version: '3'

services:
    reverse-proxy:
        image: traefik:latest
        container_name: traefik-reverse-proxy
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - ./traefik.toml:/traefik.toml
            - ${CERTIFICATES_FOLDER}:/certificates:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - frontend
        restart: unless-stopped

    nextcloud-db:
        image: postgres:latest
        container_name: nextcloud-db
        env_file: ./.servenv/nc-db-env
        volumes:
            - ${NEXTCLOUD_DB_FOLDER}:/var/lib/postgresql/data
        networks:
            - backend
        restart: unless-stopped

    nextcloud:
        image: wonderfall/nextcloud:latest
        container_name: nextcloud
        env_file: ./.servenv/nc-env
        environment:
            - UID=${NEXTCLOUD_UID}
            - GID=${NEXTCLOUD_GID}
        expose:
            - 8888
        labels:
            - traefik.enable=true
            - traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend
            - traefik.port=8888
            - traefik.frontend.rule=Host:${NEXTCLOUD_VIRTUAL_HOST}
            - traefik.backend=nextcloud
        volumes:
            - ${NEXTCLOUD_DATA_FOLDER}:/data
            - ${NEXTCLOUD_CONFIG_FOLDER}:/config
            - ${NEXTCLOUD_APP_FOLDER}:/apps2
        depends_on:
            - nextcloud-db
        links:
            - nextcloud-db
        networks:
            - frontend
            - backend
        restart: unless-stopped

    samba:
        image: dperson/samba:latest
        container_name: samba
        environment:
            - USERID=${SAMBA_UID}
            - GROUPID=${SAMBA_GID}
            - WORKGROUP=WORKGROUP
        ports:
            - 139:139
            - 445:445
        volumes:
            - ${SAMBA_SHARES_FOLDER}:/shares
        command: ${SAMBA_COMMAND}
        restart: unless-stopped

    transmission:
        image: dperson/transmission:latest
        container_name: transmission
        environment:
            - TRUSER=${TRANSMISSION_USERNAME}
            - TRPASSWD=${TRANSMISSION_PASSWORD}
            - USERID=${TRANSMISSION_UID}
            - GROUPID=${TRANSMISSION_GID}
        expose:
            - 9091
        labels:
            - traefik.enable=true
            - traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend
            - traefik.port=9091
            - traefik.frontend.rule=Host:${TRANSMISSION_VIRTUAL_HOST}
            - traefik.backend=transmission
        networks:
            - frontend
        volumes:
            - ${TRANSMISSION_INCOMPLETE_FOLDER}:/var/lib/transmission-daemon/incomplete
            - ${TRANSMISSION_DOWNLOADED_FOLDER}:/var/lib/transmission-daemon/downloads
        restart: unless-stopped

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
